sentinel_connector.settings:
  type: config_object
  label: 'Sentinel Connector settings'
  mapping:
    api_base_url:
      type: string
      label: 'Sentinel API base URL'
    site_uuid:
      type: string
      label: 'Site UUID'
    site_url:
      type: string
      label: 'Site URL'
    site_name:
      type: string
      label: 'Site name'
    site_token:
      type: string
      label: 'Site token'
    report_scope:
      type: string
      label: 'Report scope'
    cron_interval:
      type: integer
      label: 'Minimum cron interval (seconds)'
    enabled:
      type: boolean
      label: 'Enable cron sync'
